### ISSUE TITLE
enhancement - make more swifty

### ISSUE THREAD

**Issue by johndpope** [IBM-Swift/CCurl#10]
Consider cherry picking / integrating  @dmcyk wrapper. 

https://github.com/dmcyk/SwiftyCurl/blob/master/Sources/SwiftyCurl/cURLConnection.swift

**Comment by shmuelk** [comment]
Thank you very much for the suggestion.

However, our overall goal is to deprecate the CCurl repository and the APIs based on it in KituraNet, when the Foundation URLSession APIs are stable enough.

**Comment by wwe-johndpope** [comment]
@shmuelk did the nsurlsession 3.1 updates help? https://swift.org/blog/swift-3-1-released/

**Comment by shmuelk** [comment]
We haven't done so yet. Swit 3.1 still has a few warts here and there that need to be resolved.
