### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alexsteinerde** [IBM-Swift/CCurl#18]
Are there any plans to document the simple usage of this library? 
It would be nice to show some simple example in the readme to give an outlook how to use it.

**Comment by ianpartridge** [comment]
Hi, this package is a modulemap for the CCurl library, it's used to export the curl C API to Swift code in Kitura.  We wouldn't expect people to use it directly unless they want to talk directly to curl from their Swift app.  Can you explain a bit about what you want to use this package for, and what kind of info you would need?  It's a pretty niche package.

**Comment by alexsteinerde** [comment]
My goal is it to perform a delete request on a FTP server. I already found a library to upload and do other task but a delete command cannot be performed with it. So libcurl will be an solution. 
In the shim.h file I found no `curl_easy_perform` command to perform any requests.
Do I miss anything or do I not understand the handling of libcurl?
Is the `curl_easy_perform` required? Or can I even perform a delete command with CCurl?
Thanks for your support.

**Comment by ianpartridge** [comment]
Ah yes. `shim.h` exposes some helper functions that we use from inside Kitura-net. But the rest of the curl C API should be available too, for example [here is where we use it in Kitura-net](https://github.com/IBM-Swift/Kitura-net/blob/fc6e2178bba46b3209709c2e331b3ad4c402e780/Sources/KituraNet/ClientRequest.swift#L438)

If you add this package as a dependency in your Package.swift, then do `import CCurl` in your app you should be able to use the full curl API.

If that's not working people point me at the repo of your code and I'll take a look. Thanks.

**Comment by alexsteinerde** [comment]
Thanks, that sounds obvious. 
I will try my work and if I have any further questions I will ask again.
Thanks a lot for the help.

**Comment by ianpartridge** [comment]
No problem, thanks.
