### ISSUE TITLE
CCurl cannot be used outside debian systems because of .Apt

### ISSUE THREAD

**Issue by lf-araujo** [IBM-Swift/CCurl#19]
Notifying that this library cannot be loaded in linux systems other than Debian due to the use of .Apt. In my case I am trying to use /pixelspark/catena.git in an Archlinux system and it fails because of this. Are there ways of avoiding hardcoding apt-get into this library?

Thank you

**Comment by ianpartridge** [comment]
This is an SPM limitation, it hardcodes `.Apt` support. But I believe those messages are just hints and don't actually prevent the build.
